### ISSUE TITLE
Organizar menu das telas do autor Administrador

### ISSUE THREAD

**Issue by lilianeascosta** [marcosdosea/CatalogarPatrimonio#10]
Foi introduzido um botão de patrimônios para listagem, edição, visualização e criação de Patrimônio, é necessário adicionar esse  botão em todos as outras telas do autor Administrador.

**Comment by DanielSant** [comment]
Essa issue está duplicada, o issue 4 está resolvendo problemas similares a esse e irá realizar todas as mudanças. Por tanto irei fechar a issue.
