### ISSUE TITLE
Ajustar alterações do caso de uso e as alterações refletidas nos protótipos

### ISSUE THREAD

**Issue by rafael039** [marcosdosea/CatalogarPatrimonio#30]
Alteração nos autores: Administrador - Manter Empresa e Adicionar Gestor a Empresa
Administrador agora é Gestor
Gestor agora é Almoxarife

**Comment by lilianeascosta** [comment]
Fiz alteração no caso de uso do novo autor Administrador e mudanças de nomes dos outros autores

**Comment by lilianeascosta** [comment]
Fiz alteração nos analysis model seguindo recomendação de Dosea

**Comment by lilianeascosta** [comment]
fiz alterações necessárias nos modelos de analise ManterSolicitacoesServico e EntradaMaterial

**Comment by rafael039** [comment]
Falta alterar as telas !

**Comment by lilianeascosta** [comment]
Observação: ajustar os nomes das pastas e os nomes dos tipos de usuários em todas as páginas
