### ISSUE TITLE
Criar modelo DER

### ISSUE THREAD

**Issue by DanielSant** [marcosdosea/CatalogarPatrimonio#54]
A partir de todos os modelos de classes criados, ajustar o modelo de entidade relacionamento, para o projeto de banco de dados;

**Comment by lilianeascosta** [comment]
Revisei todos os modelos de análise, fiz algumas alterações que achei necessárias.

**Comment by lilianeascosta** [comment]
Puxei as entidades para o DER (surgiu alguns problemas e foi necessário revisar novamente)

**Comment by lilianeascosta** [comment]
deletei a pasta "Administrador" dentro de Requisitos>prototipos>pages. (pois esse usuário não existe mais)

**Comment by lilianeascosta** [comment]
fiz alterações nas cardinalidades das associações
