### ISSUE TITLE
Criar os diagramas de sequência para o modelo de análise.

### ISSUE THREAD

**Issue by DanielSant** [marcosdosea/CatalogarPatrimonio#57]
Criar todos os diagramas de sequencia para completar o modelo de análise, foram criadas apenas os diagramas de classe.

**Comment by lilianeascosta** [comment]
implementei o manter pessoa

**Comment by JrSts** [comment]
inseri os diagramas de sequencia dos cruds(telas manter)

**Comment by JrSts** [comment]
correcao do diagrama de classe manterMaterial

**Comment by JrSts** [comment]
correcoes no diagrama de use case

**Comment by JrSts** [comment]
criados os diagramas de sequencia de todas as funcoes de "Manter" (CRUD)
