### ISSUE TITLE
Atualizar descrição dos casos de uso

### ISSUE THREAD

**Issue by DanielSant** [marcosdosea/CatalogarPatrimonio#64]
Como houveram muitas mudanças nos protótipos precisamos ter o retrabalho de atualizar a descrição dos casos de uso a nível sistema.

**Comment by lilianeascosta** [comment]
Iniciei fazendo a descrição do caso de uso CSU03 - ManterPessoa.

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU10 - ManterMaterial.

**Comment by rafael039** [comment]
Adicionei os requisitos funcionais e não funcionais

**Comment by WagnerPrata** [comment]
Modificação do Caso de Uso  CSU04 - Manter Solicitações -

**Comment by rafael039** [comment]
Atualizei o CSU06 - Manter Locais

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU05 - AtenderSolicitacoesDeServico.

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU02 - Adicionar Gestor de Empresa

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU07 - Transferência de Material

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU07 - Entrada de Material

**Comment by WagnerPrata** [comment]
Atualização do caso de uso CSU10 - ManterMaterial

**Comment by WagnerPrata** [comment]
Atualização do caso de uso CSU12 - ManterPatrimonio

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU13 - Manter Tipo de Patrimonio

**Comment by rafael039** [comment]
Fiz a descrição do caso de uso CSU09 - Manter Fornecedor

**Comment by rafael039** [comment]
Atualização do caso de uso CSU11 - Manter Locais

**Comment by lilianeascosta** [comment]
Fiz a descrição do caso de uso CSU16 - Atender Ordens de Serviço".

**Comment by rafael039** [comment]
Fiz a descrição do caso de uso CSU14 - Manter Almoxarifado

**Comment by WagnerPrata** [comment]
Atualização da nomenclatura dos casos de Uso ManterLocais, ManterFornecedor, ManterAlmoxarifado

**Comment by WagnerPrata** [comment]
Criação do Casos de Uso - InserirNovoCadastro

**Comment by WagnerPrata** [comment]
Criação e atualização do Caso de Uso Manter Tipo de Serviço
