### ISSUE TITLE
Alterações no Kanban

### ISSUE THREAD

**Issue by JrSts** [marcosdosea/CatalogarPatrimonio#72]
Melhorar a divisão no quadro Kaban e fazer como sprints de versão, alguns estão dessa forma, achei interessante

**Comment by DanielSant** [comment]
Foi criado o quadro com a próxima demanda e versão para o projeto, e incializado com issues para alcançar esse objetivo. Ocorrerá da mesma maneira para as próximas versões. Portanto, pode fechar essa issue.

**Comment by JrSts** [comment]
Issue resolvida.
